---
title: "EMR Spot Cluster for PGx Analysis - Bulky"
author: "Jerome Dixon"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
editor: source
format:
  html:
    toc: true
    toc-depth: 5
    html-math-method: katex
    df-print: paged
    embed-resources: true
    fontsize: "11pt"
    code-fold: true
    code-summary: "Show the code"
    smooth-scroll: true
editor_options: 
  chunk_output_type: inline
execute:
  echo: true
  message: false
  warning: false
  eval: false
---

```{r sync-renv-bash}

library(jsonlite)
library(here)

cwd <- here::here()

Sys.setenv("CWD"=cwd)

```

### AWS EC2 Spot Advisor

-   This section provides a comparison between x2idn and x2iedn instance types. These are high-memory instances suitable for memory-intensive workloads. The table below shows key differences in specifications and use cases

| Feature | x2idn | x2iedn |
|------------------------|------------------------|------------------------|
| Architecture | x86_64 (Intel Cascade Lake) | Same |
| Memory per vCPU | \~8 GiB per vCPU | \~16 GiB per vCPU (2x more) |
| Memory (e.g. 16xlarge) | 512 GiB | 1,024 GiB |
| vCPUs (16xlarge) | 64 | 64 |
| Instance Storage | 1 x 1.9 TB NVMe SSD | 2 x 1.5 TB NVMe SSDs |
| Network Bandwidth | Up to 50 Gbps | Up to 100 Gbps |
| Use Case Focus | Cost-optimized memory | Max memory performance + bandwidth |
| ENA Express | No | Yes (lower latency, higher throughput) |
| Price | Lower | Higher (due to more memory, network, storage) |

-   Use case recommendations based on instance type characteristics:

Use x2idn if: - You're looking for a cost-effective high-memory instance - Your workload needs high memory but not the absolute maximum memory bandwidth - You're okay with 8 GiB/vCPU and lower network/storage

Use x2iedn if: - You need 1 TB+ of RAM and super-fast I/O - You're running in-memory databases (SAP HANA, Redis, etc.) - You're processing large model training, graph analytics, or real-time analytics - You want highest bandwidth & lowest latency networking

<https://aws.amazon.com/ec2/spot/instance-advisor/>

### Spot Pricing

```{bash}

aws ec2 describe-spot-price-history \
  --instance-types x2idn.16xlarge x2idn.24xlarge m4.16xlarge m7g.16xlarge \
  --product-descriptions "Linux/UNIX" \
  --start-time $(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --region us-east-1 \
  --query "SpotPriceHistory[*].[InstanceType,AvailabilityZone,SpotPrice]" \
  --output table

```

Note: No big price difference from 16xlarge and 24xlarge but 24xlarge is more available and therefore cheaper in a few sub-regions

-   Lowest price Instance Type

```{bash}

instance_type=$(aws ec2 describe-spot-price-history \
  --instance-types x2idn.16xlarge x2idn.24xlarge m4.16xlarge m7g.16xlarge \
  --product-descriptions "Linux/UNIX" \
  --start-time $(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --region us-east-1 \
  --query "sort_by(SpotPriceHistory, &SpotPrice)[0].[InstanceType]" \
  --output text)
  
echo "$instance_type"
echo "$instance_type" > instance.txt

```

-   Lowest Price Availability Zone

```{bash}

availability_zone=$(aws ec2 describe-spot-price-history \
  --instance-types x2idn.16xlarge x2idn.24xlarge m4.16xlarge m7g.16xlarge \
  --product-descriptions "Linux/UNIX" \
  --start-time $(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --region us-east-1 \
  --query "sort_by(SpotPriceHistory, &SpotPrice)[0].[AvailabilityZone]" \
  --output text)
  
echo "$availability_zone"
echo "$availability_zone" > zone.txt

```

-   Subnet for Lowest Price Instance in EMR VPC

```{bash}

zone_id=$(cat zone.txt)
emr_vpc_id="vpc-0ea3d9b6c6c64d0af"
  
aws ec2 describe-subnets \
  --filters "Name=availability-zone,Values=$zone_id" "Name=vpc-id,Values=$emr_vpc_id" \
  --query 'Subnets[*].[SubnetId,AvailabilityZone,VpcId]' \
  --output table


```

#### If Subnet Available in EMR VPC

```{bash}

zone_id=$(cat zone.txt)
emr_vpc_id="vpc-0ea3d9b6c6c64d0af"
  
vpc_subnet_id=$(aws ec2 describe-subnets \
  --filters "Name=availability-zone,Values=$zone_id" "Name=vpc-id,Values=$emr_vpc_id" \
  --query 'Subnets[*].[SubnetId]' \
  --output text)
  
echo "$vpc_subnet_id"
echo "$vpc_subnet_id" > vpc_subnet.txt

```

#### If Subnet Not Available

##### Describe EMR VPC

```{bash}

vpc_id="vpc-0ea3d9b6c6c64d0af"

aws ec2 describe-vpcs \
  --vpc-ids "$vpc_id" \
  --query 'Vpcs[*].[VpcId,CidrBlock,State,IsDefault]' \
  --output table

```
`

##### Add New Subnet

```{bash eval=FALSE}

vpc_id="vpc-0ea3d9b6c6c64d0af"

aws ec2 create-subnet \
  --vpc-id "$vpc_id" \
  --cidr-block 172.31.160.0/20 \
  --availability-zone us-east-1f \
  --tag-specifications 'ResourceType=subnet,Tags=[{Key=Name,Value=emr-studio-private-us-east-1f}]'


```


```{bash}

aws ec2 describe-subnets \
  --filters Name=vpc-id,Values=vpc-0ea3d9b6c6c64d0af \
           Name=tag:Name,Values=emr-studio-private-us-east-1f \
  --query "Subnets[*].SubnetId" \
  --output text > vpc_subnet.txt

```

- Ensure private

```{bash}

subnet_id=$(cat vpc_subnet.txt)

aws ec2 modify-subnet-attribute \
  --subnet-id "$subnet_id" \
  --no-map-public-ip-on-launch


```

##### Link Subnet to Routing Table

- Must use NAT Gateway

```{bash}

vpc_id="vpc-0ea3d9b6c6c64d0af"
subnet_id=$(cat new_subnet.txt)

aws ec2 describe-route-tables \
  --filters Name=vpc-id,Values="$vpc_id" \
            Name=route.nat-gateway-id,Values=* \
  --query 'RouteTables[*].{RouteTableId:RouteTableId,NatGatewayId:Routes[?NatGatewayId]|[0].NatGatewayId}' \
  --output table


```


```{bash}

aws ec2 describe-route-tables \
  --filters Name=route.nat-gateway-id,Values=* \
  --query 'RouteTables[0].RouteTableId' \
  --output text > route_table.txt


```

- Update to use Routing Table with NAT Gateway

```{bash}

subnet_id=$(cat new_subnet.txt)
route_table_id=$(cat route_table.txt)

aws ec2 associate-route-table \
  --subnet-id "$subnet_id" \
  --route-table-id "$route_table_id"


```


```{bash}

zone_id=$(cat zone.txt)

subnet_id=$(aws ec2 describe-subnets \
  --filters "Name=availability-zone,Values=$zone_id" \
  --query 'Subnets[*].[SubnetId]' \
  --output text)

echo "$subnet_id"
echo "$subnet_id" > vpc_subnet.txt

```

### Instance Fleet

```{bash}

instance_type=$(cat instance.txt)

cat > instance-fleets.json <<EOF
[
  {
    "Name": "MasterFleet",
    "InstanceFleetType": "MASTER",
    "TargetOnDemandCapacity": 0,
    "TargetSpotCapacity": 1,
    "InstanceTypeConfigs": [
      {
        "InstanceType": "$instance_type",
        "EbsConfiguration": {
          "EbsBlockDeviceConfigs": [
            {
              "VolumeSpecification": {
                "VolumeType": "gp2",
                "SizeInGB": 192
              },
              "VolumesPerInstance": 4
            }
          ]
        }
      }
    ]
  },
  {
    "Name": "CoreFleet",
    "InstanceFleetType": "CORE",
    "TargetOnDemandCapacity": 0,
    "TargetSpotCapacity": 1,
    "InstanceTypeConfigs": [
      {
        "InstanceType": "$instance_type",
        "EbsConfiguration": {
          "EbsBlockDeviceConfigs": [
            {
              "VolumeSpecification": {
                "VolumeType": "gp2",
                "SizeInGB": 192
              },
              "VolumesPerInstance": 4
            }
          ]
        }
      }
    ]
  }
]

EOF

```


```{bash}

export aws_account=535362115856
subnet_id=$(cat vpc_subnet.txt)


ec2_attrs=$(cat <<EOF
{
  "InstanceProfile": "EMR_EC2_DefaultRole",
  "EmrManagedMasterSecurityGroup": "sg-0a5260eee9a20654e",
  "EmrManagedSlaveSecurityGroup": "sg-0f01580b24ea364e1",
  "ServiceAccessSecurityGroup": "sg-0e25102a082ef38d1",
  "KeyName": "mushin_pgx",
  "SubnetId": "$subnet_id"
}
EOF
)


aws emr create-cluster \
  --name "PGx-Analysis-2025-Deep-Config" \
  --log-uri "s3://aws-logs-535362115856-us-east-1/elasticmapreduce" \
  --release-label "emr-7.5.0" \
  --service-role "arn:aws:iam::$aws_account:role/EMR_DefaultRole" \
  --security-configuration "pgx_emr2" \
  --managed-scaling-policy '{"ComputeLimits":{"UnitType":"InstanceFleetUnits","MinimumCapacityUnits":4,"MaximumCapacityUnits":30,"MaximumOnDemandCapacityUnits":0,"MaximumCoreCapacityUnits":25}}' \
  --unhealthy-node-replacement \
  --ec2-attributes "$ec2_attrs" \
  --applications Name=Hadoop Name=Hive Name=JupyterEnterpriseGateway Name=Livy Name=Spark \
  --configurations file://config/emr_config.json \
  --instance-fleets file://instance-fleets.json \
  --bootstrap-actions '[{"Args":[],"Name":"pgx","Path":"s3://pgx-repository/emr-config/emr_bootstrap.sh"}]' \
  --scale-down-behavior "TERMINATE_AT_TASK_COMPLETION" \
  --ebs-root-volume-size "97" \
  --auto-termination-policy '{"IdleTimeout":3600}' \
  --region "us-east-1"

```

#### EMR Deep Configuration

```{python eval=FALSE}

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import IntegerType, DoubleType
from pyspark.sql.functions import col, max as spark_max, min as spark_min
import os


# Dynamically detect NVMe mount points
available_mounts = []
for candidate in ["/mnt", "/mnt1", "/mnt2", "/mnt3", "/mnt4", "/mnt5"]:
    if os.path.exists(candidate):
        available_mounts.append(candidate)

local_dirs = ",".join(available_mounts)

spark = SparkSession.builder \
    .appName("PGx_Cohort_Dataset_Builder") \
    .config("spark.executor.cores", "16") \
    .config("spark.executor.memory", "50g") \
    .config("spark.executor.memoryOverhead", "12g") \
    .config("spark.driver.memory", "64g") \
    .config("spark.driver.memoryOverhead", "8g") \
    .config("spark.memory.offHeap.enabled", "true") \
    .config("spark.memory.offHeap.size", "10g") \
    .config("spark.default.parallelism", "1200") \
    .config("spark.sql.shuffle.partitions", "512") \
    .config("spark.shuffle.spill.compress", "true") \
    .config("spark.shuffle.compress", "true") \
    .config("spark.io.compression.codec", "lz4") \
    .config("spark.dynamicAllocation.enabled", "true") \
    .config("spark.dynamicAllocation.executorIdleTimeout", "60s") \
    .config("spark.dynamicAllocation.schedulerBacklogTimeout", "1s") \
    .config("spark.task.cpus", "2") \
    .config("spark.sql.adaptive.enabled", "true") \
    .config("spark.sql.adaptive.shuffle.targetPostShuffleInputSize", "256MB") \
    .config("spark.sql.adaptive.advisoryPartitionSizeInBytes", "64MB") \
    .config("spark.sql.adaptive.skewJoin.enabled", "true") \
    .config("spark.network.timeout", "1200s") \
    .config("spark.rpc.askTimeout", "600s") \
    .config("spark.executor.extraJavaOptions", "-XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=35") \
    .config("spark.local.dir", local_dirs) \
    .getOrCreate()




```

